verbose: 1
N: 20000
N_POP: 2
K: 1000.0

FRAC: [0.5, 0.5]

DT: 0.1
DURATION: 5000.0
T_WINDOW: 10.
T_STEADY: 2000.0

T_STIM: [3000.0, 4000.0]
A_STIM: [1.0, 0.0]
PHI_STIM: [180.0, 0.0]
KAPPA_STIM: [0.5, 0.0]

##############
# Dynamics
##############
V_THRESH: 20.0
V_REST: -3.33
V_LEAK: 0.0

TAU_MEM: [20.0, 10.0]
TAU_SYN: [3.0, 2.0]

IF_NMDA: 1
TAU_NMDA: [80.0, 40.0]

##############
# Parameters
##############
GAIN: 1.0

# Iext: [0.01, 0.05]
# Jab: [30.0, -1.25, 1.0, -1.0]

# Iext: [77, 54]
# Jab: [90.0, -1.4, 1.2, -0.90]

Iext: [.05, 0.045]
Jab: [40.0, -2.8, 6.7, -3.4]

# Iext: [.005, .0025]
# Jab: [2.0, -0.18, 0.25, -0.20]

# Iext: [19.98, 12.798]
# Jab: [52.7277, -66.5861, 7.31482, -42.8053]

##############
# CONNECTIVITY
##############
IF_LOAD_MAT: 0
IF_SAVE_MAT: 1

# PROBA: spec
# KAPPA: [15.0, 0.0, 0.0, 0.0]

PROBA: cos
KAPPA: [1.0, 1.0, 0.5, 1.0]

##############
# STP
##############
IF_STP: 1
USE: [0.03, 0.05]
TAU_FAC: [750, 750]
TAU_REC: [200, 200]

##############
# FF
##############
IF_FF_NOISE: 0
VAR_FF: [5.0, 5.0]

