verbose: 1
N: 5000
N_POP: 2
K: 250.0

FRAC: [0.5, 0.5]

DT: 0.1
DURATION: 3000.0
T_WINDOW: 10.

T_STIM: [1000.0, 1500.0]
A_STIM: [5.0, 0.0]
PHI_STIM: [90.0, 0.0]
KAPPA_STIM: [1.0, 0.0]

V_THRESH: 20.0
V_REST: -3.33
V_LEAK: 0.0

TAU_MEM: [20.0, 10.0]
TAU_SYN: [3.0, 2.0]

GAIN: 1.0
Iext: [4.0, 2.0]
Jab: [300.0, -1.5, 1.0, -1.0]

# Iext: [1.0, 0.5]
# Jab: [0.44, -0.28, 0.67, -0.34]

IF_STP: 1
USE: [0.05, 0.05]
TAU_FAC: [650, 650]
TAU_REC: [250, 250]

PROBA: spec
KAPPA: [5.0, 0.0, 0.0, 0.0]

# PROBA: cos
# KAPPA: [0.5, 0.5, 0.5, 0.5]

IF_FF_NOISE: 1
VAR_FF: [5.0, 5.0]