verbose: 1
N: 10000
N_POP: 2
K: 500.0

FRAC: [0.75, 0.25]

DT: 0.1
DURATION: 4000.0
T_WINDOW: 10.
T_STEADY: 1000.0

T_STIM: [2000.0, 3000.0]
A_STIM: [20.0, 0.0]
PHI_STIM: [180.0, 0.0]
KAPPA_STIM: [0.5, 0.0]

##############
# Dynamics
##############
V_THRESH: 20.0
V_REST: -3.33
V_LEAK: 0.0

TAU_MEM: [20.0, 10.0]
TAU_SYN: [3.0, 2.0]

IF_NMDA: 1
TAU_NMDA: [80.0, 40.0]

##############
# Parameters
##############
GAIN: 1.0

# Iext: [10.0, 5.0]
# Jab: [300.0, -1.25, 1.0, -1.0]

Iext: [770, 540]
Jab: [900.0, -140.0, 120, -90.0]

# Iext: [1.0, 0.5]
# Jab: [60.0, -0.28, 0.67, -0.34]

# Iext: [1.0, 1.0]
# Jab: [1.92, -0.18, 0.25, -0.20]

##############
# CONNECTIVITY
##############
# PROBA: spec
# KAPPA: [15.0, 0.0, 0.0, 0.0]

PROBA: cos
KAPPA: [1.0, 1.0, 0.85, 1.0]

##############
# STP
##############
IF_STP: 1
USE: [0.000055, 0.05]
TAU_FAC: [750, 750]
TAU_REC: [200, 200]

##############
# FF
##############
IF_FF_NOISE: 0
VAR_FF: [5.0, 5.0]