A_STIM:
- 1.0
- 0.0
DATA_PATH: ../data/simul
DT: 0.1
DURATION: 20000.0
FRAC:
- 0.75
- 0.25
GAIN: 1.0
IF_FF_NOISE: 0
IF_LOAD_MAT: 1
IF_NMDA: 1
IF_SAVE_MAT: 0
IF_STP: 1
Iext:
- 0.005
- 0.0025
Jab:
- 42.0
- -2.8
- 6.7
- -3.4
K: 2000.0
KAPPA:
- 1.0
- 1.0
- 1.0
- 1.0
KAPPA_STIM:
- 1.0
- 0.0
MAT_PATH: ./data/matrix
N: 40000
N_POP: 2
PHI_STIM:
- 180.0
- 0.0
PROBA: cos
R_NMDA:
- 0.5
- 0.5
TAU_FAC:
- 750
- 750
TAU_MEM:
- 20.0
- 10.0
TAU_NMDA:
- 100.0
- 50.0
TAU_REC:
- 200
- 200
TAU_SYN:
- 4.0
- 2.0
T_STEADY: 10000.0
T_STIM:
- 3000.0
- 4000.0
T_WINDOW: 10.0
USE:
- 0.05
- 0.05
VAR_FF:
- 5.0
- 5.0
V_LEAK: 0.0
V_REST: -70.0
V_THRESH: -50.0
verbose: 1
