DATA_PATH: /home/leon/models/lif_cpp/data/simul
MAT_PATH: /home/leon/models/lif_cpp/data/matrix

verbose: 1
N: 40000
N_POP: 2
K: 2000.0

FRAC: [0.75, 0.25]

DT: 0.1
DURATION: 61000.0
T_WINDOW: 250.
T_STEADY: 5000.0

#################
# Stimulus
#################
T_STIM: [6000.0, 7000.0]
A_STIM: [.075, 0.0]
PHI_STIM: [180.0, 0.0]
KAPPA_STIM: [1.0, 0.0]

##############
# Dynamics
##############
V_THRESH: -50.0
V_REST: -70.0
V_LEAK: 0.0

TAU_MEM: [20.0, 10.0]
TAU_SYN: [4.0, 2.0]

IF_NMDA: 1
TAU_NMDA: [100.0, 50.0]
R_NMDA: [0.5, 0.5]

##############
# Parameters
##############
GAIN: 1.0

# Iext: [0.005, 0.005]
# Jab: [1.0, -1.5, 1.0, -1.0]

# Iext: [0.005, 0.0025]
# Jab: [20.0, -1.4, 1.2, -0.90]

# Iext: [.005, 0.0025]
# Jab: [42.0, -2.8, 6.7, -3.4]

Iext: [.004, 0.002]
# Jab: [43.0, -2.8, 6.7, -3.4]
Jab: [20.0, -1.4, 2.8, -1.7]

##############
# CONNECTIVITY
##############
IF_LOAD_MAT: 1
IF_SAVE_MAT: 0

# PROBA: spec
# KAPPA: [10.0, 0.0, 0.0, 0.0]

PROBA: cos
KAPPA: [1.0, 0.95, 1.0, 1.0]

##############
# STP
##############
IF_STP: 1
USE: [0.03, 0.03]
TAU_FAC: [650, 650]
TAU_REC: [200, 200]

##############
# FF
##############
IF_FF_NOISE: 0
VAR_FF: [1.0, 1.0]

IF_FF_CORR: 0
A_CORR: [0.5, 0.5]
CORR_FF: [0.5, 0.5]
