A_CORR:
- 0.0025
- 0.0025
A_DIST:
- 0.0
- 0.0
A_STIM:
- 0.2
- 0.0
BUMP_SWITCH:
- 0
- 0
CHECK_BISTABILITY: 0
CORR_FF:
- 0.25
- 0.25
DATA_PATH: /home/leon/models/lif_cpp/data/simul/odr_Ie_2.80_phi_180_ini_32
DT: 0.1
DURATION: 6000.0
FRAC:
- 0.8
- 0.2
GAIN: 1.0
IF_FF_CORR: 0
IF_FF_NOISE: 1
IF_LOAD_MAT: 1
IF_NMDA: 1
IF_SAVE_DATA: 1
IF_SAVE_MAT: 0
IF_STP: 1
Iext:
- 0.0028
- 0.00175
Jab:
- 7.5
- -1.35
- 1.25
- -2.0
K: 4000.0
KAPPA:
- 0.5
- 0.45
- 0.5
- 0.5
KAPPA_DIST:
- 0.0
- 0.0
KAPPA_STIM:
- 0.5
- 0.0
LR_LOAD: 0
LR_MEAN:
- 0.0
- 0.0
- 0.0
LR_RANK: 3
LR_RHO:
- 0.0
- 1.0
- 0.0
LR_SEED: 1
LR_STD:
- 1.0
- 1.0
- 1.0
MAT_PATH: /home/leon/models/lif_cpp/data/matrix
N: 40000
N_POP: 2
PHI_DIST:
- 90.0
- 0.0
PHI_STIM:
- 180.0
- 0.0
PROBA:
- cos
- cos
- cos
- cos
R_NMDA:
- 0.5
- 0.5
STD_DIST:
- 0.0
- 0.0
STD_FF:
- 2.5e-05
- 2.5e-05
STD_STIM:
- 0.0
- 0.0
TAU_FAC:
- 550
- 850
TAU_MEM:
- 20.0
- 10.0
TAU_NMDA:
- 80.0
- 40.0
TAU_REC:
- 250
- 200
TAU_SYN:
- 4.0
- 2.0
T_DIST:
- 13500.0
- 14500.0
T_SAVE: 500.0
T_STEADY: 5000.0
T_STIM:
- 1000.0
- 1500.0
T_WINDOW: 250.0
USE:
- 0.03
- 0.03
V_LEAK: 0.0
V_REST: -70.0
V_THRESH: -50.0
verbose: 1
