DATA_PATH: /home/leon/models/lif_cpp/data/simul
MAT_PATH: /home/leon/models/lif_cpp/data/matrix

verbose: 1
N: 40000
N_POP: 2
K: 2000.0

FRAC: [0.75, 0.25]

DT: 0.1
DURATION: 25000.0
T_WINDOW: 250.
T_STEADY: 5000.0

#################
# Stimulus
#################
T_STIM: [7000.0, 8000.0]
A_STIM: [.075, 0.0]
PHI_STIM: [180.0, 0.0]
KAPPA_STIM: [1.0, 0.0]

##############
# Dynamics
##############
V_THRESH: -50.0
V_REST: -70.0
V_LEAK: 0.0

TAU_MEM: [20.0, 10.0]
TAU_SYN: [4.0, 2.0]

IF_NMDA: 1
TAU_NMDA: [100.0, 50.0]
R_NMDA: [0.5, 0.5]

##############
# Parameters
##############
GAIN: 1.0

# Iext: [0.01, 0.05]
# Jab: [30.0, -1.25, 1.0, -1.0]

# Iext: [.077, .054]
# Jab: [90.0, -1.4, 1.2, -0.90]

# Iext: [.005, 0.0025]
# Jab: [42.0, -2.8, 6.7, -3.4]

Iext: [.004, 0.002]
# Jab: [43.0, -2.8, 6.7, -3.4]
# Jab: [19.0, -1.4, 3.35, -1.7]

Jab: [9.5, -0.7, 1.675, -0.85]
# Iext: [.005, .0025]
# Jab: [2.0, -0.18, 0.25, -0.20]

# Iext: [19.98, 12.798]
# Jab: [52.7277, -66.5861, 7.31482, -42.8053]

##############
# CONNECTIVITY
##############
IF_LOAD_MAT: 1
IF_SAVE_MAT: 0

# PROBA: spec
# KAPPA: [10.0, 0.0, 0.0, 0.0]

PROBA: cos
KAPPA: [1.0, 0.95, 1.0, 1.0]

##############
# STP
##############
IF_STP: 1
USE: [0.05, 0.05]
TAU_FAC: [650, 650]
TAU_REC: [200, 200]

##############
# FF
##############
IF_FF_NOISE: 0
VAR_FF: [1.0, 1.0]

IF_FF_CORR: 1
CORR_FF: [2.5, 2.5]
